development:
  sessions:
    default:
      database: demo
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
    raise_not_found_error: false
production:
  sessions:
    default:
      database: demo
      hosts:
        - 127.0.0.1:27017
      options:
        consistency: :eventual
        raise_not_found_error: false 